import type { Metadata, Viewport } from "next";
import { Lato, Libre_Baskerville } from "next/font/google";
import Script from 'next/script';
import "./globals.css";

/**
 * Configure Lato font for body text
 * - The variable name becomes a CSS variable in :root
 * - Optimizes font loading and reduces layout shift
 */
const lato = Lato({
  variable: "--font-lato", // Creates CSS variable for use in globals.css
  subsets: ["latin"],      // Loads only Latin character subset for performance
  weight: ["400", "700"],  // Load only regular and bold weights to reduce bundle size
});

/**
 * Configure Libre Baskerville for logo and headings
 * - Adds an elegant, serif font for contrast with body text
 * - Loads minimal weights to optimize performance
 */
const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville", // Creates CSS variable for use in globals.css
  subsets: ["latin"],                   // Loads only Latin character subset
  weight: ["400", "700"],               // Load only regular and bold weights
});

/**
 * Site-wide metadata configuration
 * - Sets document title, description, and favicon
 * - These values are used for SEO and browser tabs
 */
export const metadata: Metadata = {
  title: "Chiroport",                      // Browser tab title
  description: "Generated by create next app", // Description for search engines
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/icons/favicon-32x32.png', sizes: '32x32', type: 'image/png' }
    ],
  },
};

/**
 * Viewport configuration for responsive design
 * - Controls how the site appears on different devices
 * - Proper scaling settings for mobile compatibility
 */
export const viewport: Viewport = {
  width: 'device-width',        // Makes site responsive to device width
  initialScale: 1,              // Initial zoom level when page loads
  maximumScale: 5,              // Maximum zoom level allowed
};

/**
 * Root layout component
 * - Wraps all pages in the app
 * - Provides font variables and basic HTML structure
 * - Applied consistently across all routes
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icons/favicon-32x32.png" sizes="32x32" type="image/png" />
        {/* Waitwhile inline-embed library */}
        <Script
          src="https://cdn.jsdelivr.net/npm/@waitwhile/waitwhile-embed/dist/waitwhile-embed.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className={`${lato.variable} ${libreBaskerville.variable} antialiased max-w-full overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
